import { Product } from "@/contexts/cart-context"

export const products: Product[] = [
  {
    id: "1",
    name: "Farm Fresh Milk",
    price: 60,
    image: "/products/milk.jpg",
    category: "Milk",
    description: "Pure and fresh cow milk delivered straight from the farm. Rich in calcium and protein.",
    unit: "1 Liter",
  },
  {
    id: "2",
    name: "Organic Toned Milk",
    price: 55,
    image: "/products/toned-milk.jpg",
    category: "Milk",
    description: "Low-fat toned milk with all the goodness of regular milk. Perfect for health-conscious families.",
    unit: "1 Liter",
  },
  {
    id: "3",
    name: "Buffalo Milk",
    price: 75,
    image: "/products/buffalo-milk.jpg",
    category: "Milk",
    description: "Creamy and thick buffalo milk. Great for making paneer and sweets.",
    unit: "1 Liter",
  },
  {
    id: "4",
    name: "Fresh Cream",
    price: 120,
    image: "/products/cream.jpg",
    category: "Cream",
    description: "Rich and thick fresh cream. Perfect for desserts and coffee.",
    unit: "200ml",
  },
  {
    id: "5",
    name: "Greek Yogurt",
    price: 90,
    image: "/products/yogurt.jpg",
    category: "Yogurt",
    description: "Thick and creamy Greek yogurt. High in protein and probiotics.",
    unit: "400g",
  },
  {
    id: "6",
    name: "Natural Curd",
    price: 45,
    image: "/products/curd.jpg",
    category: "Yogurt",
    description: "Fresh homemade style curd. Perfect for daily consumption.",
    unit: "500g",
  },
  {
    id: "7",
    name: "Cottage Cheese (Paneer)",
    price: 180,
    image: "/products/paneer.jpg",
    category: "Cheese",
    description: "Fresh and soft cottage cheese. Perfect for Indian dishes.",
    unit: "200g",
  },
  {
    id: "8",
    name: "Cheddar Cheese",
    price: 250,
    image: "/products/cheddar.jpg",
    category: "Cheese",
    description: "Aged cheddar cheese with rich flavor. Great for sandwiches and burgers.",
    unit: "200g",
  },
  {
    id: "9",
    name: "Mozzarella Cheese",
    price: 220,
    image: "/products/mozzarella.jpg",
    category: "Cheese",
    description: "Stretchy mozzarella cheese. Perfect for pizzas and pasta.",
    unit: "200g",
  },
  {
    id: "10",
    name: "Pure Ghee",
    price: 550,
    image: "/products/ghee.jpg",
    category: "Ghee & Butter",
    description: "Traditional cow ghee made from pure butter. Rich aroma and taste.",
    unit: "500ml",
  },
  {
    id: "11",
    name: "Salted Butter",
    price: 150,
    image: "/products/butter.jpg",
    category: "Ghee & Butter",
    description: "Creamy salted butter. Perfect for bread and cooking.",
    unit: "200g",
  },
  {
    id: "12",
    name: "Buttermilk",
    price: 35,
    image: "/products/buttermilk.jpg",
    category: "Beverages",
    description: "Refreshing spiced buttermilk. Great for digestion.",
    unit: "500ml",
  },
  {
    id: "13",
    name: "Chocolate Milk",
    price: 50,
    image: "/products/chocolate-milk.jpg",
    category: "Beverages",
    description: "Delicious chocolate flavored milk. Kids favorite!",
    unit: "250ml",
  },
  {
    id: "14",
    name: "Lassi (Sweet)",
    price: 45,
    image: "/products/lassi.jpg",
    category: "Beverages",
    description: "Traditional sweet lassi. Refreshing and nutritious.",
    unit: "300ml",
  },
  {
    id: "15",
    name: "Flavored Yogurt (Mango)",
    price: 55,
    image: "/products/mango-yogurt.jpg",
    category: "Yogurt",
    description: "Creamy yogurt with real mango flavor. Perfect snack.",
    unit: "150g",
  },
  {
    id: "16",
    name: "A2 Cow Milk",
    price: 85,
    image: "/products/a2-milk.jpg",
    category: "Milk",
    description: "Premium A2 protein milk from indigenous cows. Easy to digest.",
    unit: "1 Liter",
  },
]

export const categories = [
  "All",
  "Milk",
  "Yogurt",
  "Cheese",
  "Ghee & Butter",
  "Cream",
  "Beverages",
]

export const offers = [
  {
    id: "1",
    title: "First Order Discount",
    description: "Get 20% off on your first order",
    code: "FIRST20",
    discount: 20,
    minOrder: 200,
    validTill: "2026-05-31",
    image: "/offers/first-order.jpg",
  },
  {
    id: "2",
    title: "Subscribe & Save",
    description: "Get 15% off on all subscription orders",
    code: "SUBSCRIBE15",
    discount: 15,
    minOrder: 0,
    validTill: "2026-12-31",
    image: "/offers/subscribe.jpg",
  },
  {
    id: "3",
    title: "Weekend Special",
    description: "Flat Rs.50 off on orders above Rs.500",
    code: "WEEKEND50",
    discount: 50,
    minOrder: 500,
    validTill: "2026-05-15",
    image: "/offers/weekend.jpg",
  },
  {
    id: "4",
    title: "Milk Lover",
    description: "Buy 5 liters of milk, get 1 liter free",
    code: "MILK6",
    discount: 0,
    minOrder: 300,
    validTill: "2026-06-30",
    image: "/offers/milk-lover.jpg",
  },
]
